### ISSUE TITLE
Could you provide us with the complete KITTI-C dataset?

### ISSUE THREAD

**Issue by heegwang27** [Hongbin98/MonoTTA#4]
It seems like the data only includes Gaussian corruption. 
Could you provide us with the complete KITTI-C dataset?

**Comment by Hongbin98** [comment]
Thanks for your attention to our work. All datasets in this paper will be public in the future~

However, I am still looking for a reliable way to share these files (~= 4~6GB * 13) with my readers due to the limitation of Google Drive.

It is also worth mentioning that you can prepare the kitti-c dataset yourself by following this link: https://github.com/hendrycks/robustness.

**Comment by heegwang27** [comment]
Thank you for your response. I look forward to accessing the data in the future. 

I have a question though—when I look at Figure 1 in the supplementary material of the paper, the KITTI-C dataset seems to appear as BGR images. 

Is there a specific reason for this? Additionally, why is only the "pixelate" corruption in RGB format?

**Comment by Hongbin98** [comment]
You can check this link for the data 'We have released the full KITTI-C dataset in huggingface! Please check the link for more: https://huggingface.co/datasets/anthemlin/kitti-c' :)

For your doubt of the "pixelate" corruption, you may check this paper '_Benchmarking Neural Network Robustness to Common Corruptions and Perturbations_' for more details.

**Comment by heegwang27** [comment]
Thank you very much for your kindness. Thanks to your help, I was able to download and check the data. 
However, I still have a question: it seems that the R and B channels in the KITTI-C dataset have been swapped. 
For example, a red car in the original dataset appears blue in this dataset. 
Is there a specific reason for swapping the R and B channels? 
I couldn't find any mention of this in the paper you referred to. Thank you :)

**Comment by Hongbin98** [comment]
I see what you mean, I will check the generated data and correct how the image is saved (One possible reason is that the default setting of opencv-python does not meet my requirements).
Thank you for kindly pointing out this issue~ I will update the kitti-c dataset once this minor issue is solved.
